project:
  type: book

book:
  title: "ASU Dissertation"
  author: "Nicole Brewer"
  date: "8/13/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    toc: false 
    include-in-header: tex/header.tex
    format-resources:
      - tex/asudis.bst
      - tex/asudis.sty
    template-partials:
      - tex/doc-class.tex
      - tex/title.tex
      - tex/before-body.tex
      - tex/toc.tex
      - tex/biblio.tex
      - tex/after-body.tex
