project:
  type: book

book:
  title: "My Amazing ASU Dissertation"
  subtitle: "An important subtitle" # if you have a subsubtitle, format like "Subtitle \\ \ \\ Subsubtitle"
  author: "Nicole Brewer" # full name
  date: "April 15, 2026" # defense date
  event-date: "May 15, 2026" # graduation date
  date-format: "MMMM, YYYY"

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  abstract: | 
  description: "Description metadata for HTML version of book"
  sharing:
    - twitter
    - linkedin
  downloads: pdf
  composer: Manfred Laubichler
  editor: Jane Maienschein
  # note:
  # url:
  # favicon:
  # output-file: basename
  # cover-image: image.png #Cover image (used in HTML and ePub formats)	
  # cover-image-alt: image.png #Alternative text for cover image (used in HTML format)

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    toc: false 
    keep-tex: true
    include-in-header: tex/header.tex
    format-resources:
      - tex/asudis.bst
      - tex/asudis.sty
    template-partials:
      - tex/doc-class.tex
      - tex/title.tex
      - tex/before-body.tex
      - tex/toc.tex
      - tex/biblio.tex
      - tex/after-body.tex
